[workspace]
members = ["src-tauri", "crates/ghost-meta"]
resolver = "2"

[workspace.dependencies]
encoding_rs = "0.8"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
opt-level = "s"
panic = "abort"
